### ISSUE TITLE
Parameter format

### ISSUE THREAD

**Issue by lukedeo** [dguest/lw-client#1]
I was thinking, it would be really cool to support both Keras style configurations and AGILEPack style. It wouldn't be too hard to support like 95% of Keras layers so we don't have to be married to AGILEPack...

**Comment by dguest** [comment]
Yeah, the idea is to make it simple enough that extending it is trivial. Can you send me an example of the Karas configuration so I can take a look?

**Comment by dguest** [comment]
Closed this since it's asking for the same thing as #3
